server:
  port: 8081
spring:
  application:
    name: client1
eureka:
  client:
    securePortEnabled: true
    ssl:
      key-store: client.p12
      key-store-password: c123456
    service-url:
      defaultZone: https://localhost:8761/eureka/